### ISSUE TITLE
Adding episodes from a show's back catalogue into the playlist

### ISSUE THREAD

**Issue by jordanl** [einmalfel/PodListen#10]
Maybe this feature exists and I'm just missing how to do it, but I'd like to scroll through a show's back catalogue (ie its RSS feed's contents) and pick random episodes into the playlist.

Use cases:
1. I'd like to go back to an older show where they talked about X and listen to it again.
2. In the New Episodes page I accidentally deleted the wrong new episode, so now it's gone forever

The "New Episodes" page is good at fetching episode summaries as they come out, but AFAICT there's not a way to see random episodes?

**Comment by einmalfel** [comment]
You are right, this feature is absent, which surprises PodListen users (I’ve received 5-6 requests already). And I agree, PodListen is incomplete without it.
The reason why I hesitate to implemented it is that it’s hard to do without breaking 3-tab brevity of PodListen.
My original intention was to design an interface simplified enough to be usable on the run. This means that user
 * switches between screens as seldom as possible
 * uses no menu for navigation
 * does basic actions with single tap

As feature you are talking about will probably be used often, there should be no separate screen for it. Fourth tab is not an option too.
Currently I’m considering to options:
 * compactly list latest episodes titles below description on expanded subscription, along with publication dates and add/remove mini-buttons. After say 10th episode there is “Show more episodes” button which expands list further
 * add a button on the right side of subscription list element. The button invokes a dialog which consist solely of list of episodes with add/remove buttons. The dialog is better than separate screen because it’s easier to dismiss it

If you (or anybody who reads this) have an opinion about how this feature should appear in PodListen, please leave a comment.

**Comment by einmalfel** [comment]
@jordanl You are right, this feature is absent, which surprises PodListen users (I’ve received 5-6 requests already). And I agree, PodListen is incomplete without it.
The reason why I hesitate to implemented it is that it’s hard to do without breaking 3-tab brevity of PodListen.
My original intention was to design an interface simplified enough to be usable on the run. This means that user
 * switches between screens as seldom as possible
 * uses no menu for navigation
 * does basic actions with single tap

As feature you are talking about will probably be used often, there should be no separate screen for it. Fourth tab is not an option too.
Currently I’m considering to options:
 * compactly list latest episodes titles below description on expanded subscription, along with publication dates and add/remove mini-buttons. After say 10th episode there is “Show more episodes” button which expands list further
 * add a button on the right side of subscription list element. The button invokes a dialog which consist solely of list of episodes with add/remove buttons. The dialog is better than separate screen because it’s easier to dismiss it

If you (or anybody who reads this) have an opinion about how this feature should appear in PodListen, please leave a comment.

**Comment by jordanl** [comment]
@einmalfel, thanks for the quick reply!

My opinion would be for the subscription list dialog. That approach works well in PodKicker, another three-tab (but nonfree) podcatcher.

**Comment by bugmenot2** [comment]
How abouuuut... You show old episodes below new episodes (maybe rename the "new episodes" tab to just "episodes" or "add episodes" at least "newest episodes"), but you make the old/downloaded/added/listenedto (your call) ones semi-transparent. You'd have to renounce the "remove all" button, but honestly,I think that's a good thing. I've deleted many a list trying to figure out what the strange "menu" icon meant. How far do you go into the past, you ask? That's the beauty of it: The "infinite scroll" knows!

The downside of this is that you have to scroll through all episodes of all podcasts. The way to solve *that* problem is to enable selecting podcast(s) as filter(s) (btw. I'd reverse the tabs order to show progression from the more general to the more specific [the Playlist could still have focus though]). You could clear the filter by clicking on some bar below tabs, or you could just go back (left!) to the Podcasts tab and clear change your selection into nothing (or into something else).

I'm eager to hear what you think about this. I think I've been respectful enough to your original design idea :)

**Comment by einmalfel** [comment]
@bugmenot2 Hmm, I don't think the feature "filter episodes by multiple subscriptions" will be used often (mostly we need to show episodes of single feed), but this indeed is a way to keep it within 3 tabs!
One disadvantage I see is that in this case contents of current episode tab may depend on state of invisible subscriptions tab which is not so indicative and user will need to switch back and forth to set filter and see result.

**Comment by bugmenot2** [comment]
The reason why I thought it would be nice to filter by multiple subscriptions is that this would allow one to listen to feeds of a certain theme at one time (eg. while commuting), and of another at another time (eg. while being able to concentrate better).

**Comment by einmalfel** [comment]
@jordanl @bugmenot2 For a start I made easiest implementation - simple dialog that pops up when user presses button in subscription list element. Each episode of podcast is shown and it's possible to delete/add episodes to playlist. Will much appreciate a feedback on this new feature :)
Update (v1.3.0) is available on Google. F-Droid will probably pick it up within two days.

**Comment by bugmenot2** [comment]
simple but/and effective. can close issue afai am concerned
