### ISSUE TITLE
Add "open file" dialog fallback implementation

### ISSUE THREAD

**Issue by schapira** [einmalfel/PodListen#6]
Using 4.2.2

**Comment by einmalfel** [comment]
Could you please elaborate a little bit more on what exactly is wrong? Do you see "Please install file manager" message when trying to open OPML file?

**Comment by bugmenot2** [comment]
I may be able to help. I had to add stuff per-feed too (despite having an OPML file). My system offers me to "Select OPML File" using the Gallery app or the music app. :/

**Comment by einmalfel** [comment]
@bugmenot2 Did system offered you ONLY gallery and music? Do you have any file manager app installed and, if yes, which one?

**Comment by bugmenot2** [comment]
Yes, only those two options. I have the default file manager going by "My Files". That's this one:
![icon](http://imgsrv.worldstart.com/images/ct-images/2014/02/2014-02-09-04.06.20-450x367.png)
This is its root view:
![app](http://www.smartmobilephonesolutions.com/sites/default/files/styles/large/public/samsung-galaxy-s-4-my-files-list-all-files-option-selected.png?itok=nRPoQ00n)

**Comment by einmalfel** [comment]
@bugmenot2 Thanks for help. The problem is that there is no standard way to invoke "open file" dialog in Android (it's a shame IMO). Some apps do provide this functionality (including music, gallery and most of file manager apps) but they respond to different types of open-file requests. So, I'm trying to send as broad open-file request as possible in a hope that one of the apps that Android offers will help user to open file.
Sadly, you "My Files" app doesn't respond to any of such requests.
I'll keep this issue open, maybe later I will include "open file" dialog implementation in PodListen.

**Comment by bugmenot2** [comment]
Speaking of importing OPML, I think the user should be able to import from a URL (which is what I tried to do and failed), so maybe instead of "Paste feed URL here", make it "Paste feed/OPML URL here", or alternatively "Paste feed(s) URL here"?

P.S. Not sure how exactly the file picker works, but if what you're doing is sending a mime-type, maybe consider sending one specific one that you can be sure the default FM will handle, and which makes sense, instead of going for broadness.

**Comment by einmalfel** [comment]
@bugmenot2 
1. Import OPML by URL is in my todo list
2. I'm sending intent with action "android.intent.action.GET_CONTENT" and MIME-type "*/*" which matches majority of FMs.
3. Again, there is no intent that I can be sure default FM will handle. Regarding your default FM, I'm sure it doesn't respond to any open-file intents at all (I have it preinstalled on my device too. I read its AndroidManifest.xml).
4. When I make open-file dialog fallback, I'll switch to "narrower" intent, which will match less apps but it won't be a problem any more.
5. Any PodListen-related discussions are welcome :)

**Comment by bugmenot2** [comment]
Cool/Weird/Thanks

**Comment by bugmenot2** [comment]
i reinstalled pl recently bc it was crashing mby bc i messed w dirs anyway i was able to import opml from a file:// url (couldnt do it w a fm). only feed icons wrnt downloaded
from mobile

**Comment by einmalfel** [comment]
@bugmenot2 Yes, it currently accepts local URLs ("file://", "content://" and "android.resource://") for OPML import

**Comment by bugmenot2** [comment]
and not remote? how come?

**Comment by einmalfel** [comment]
@bugmenot2 Android's ContentResolver facility accepts these schemes. I need to use it cause it's the only way to read "content://" URLs returned by open-file dialogs of some FM apps.

**Comment by bugmenot2** [comment]
icons loaded after dling v1.2.5

**Comment by einmalfel** [comment]
@schapira @bugmenot2 fixed in update 1.3.2

**Comment by bugmenot2** [comment]
why tirquois instead of the usual secondary color (orange) though?

**Comment by einmalfel** [comment]
@bugmenot2 Default dark material theme (on which PodListen theme is based) uses tirquois as accent color. Accent color is used for scrollbar thumbs, highlighted URLs and d/l progressbar. I've added second accent color to emphasize playback progress, FAB and error messages. Orange is kind of color of danger, that's why I think tirquois is better for folder icon

**Comment by bugmenot2** [comment]
why's progress dangerous, what's fab? i'd rather use the system color as accent for everything or -equally consistently-my own. otherwise the secondary accent color should be dynamic to go well with the system color. but this is a class example of a bikeshed, so my bad. any plans for playback speed control in the near future?

**Comment by einmalfel** [comment]
@bugmenot2 FAB stands for floating action button. Both accent colors are static. "Dangerous" color is bad for folder icon because I suspect that user could react subconsciously like "hey what's wrong with my folders". Regarding playback speed see #9

**Comment by bugmenot2** [comment]
honestly if i thought orange was dangerous i wouldn't have acidentally cleared the list of episodes before there was a way to bring them back... twice. looks more lika a material design thing to me. surely opening the subscription dialog is safe. sorry if i sound cranky
