### ISSUE TITLE
Episodes in playlist are deleted after a while

### ISSUE THREAD

**Issue by lothar-mar** [einmalfel/PodListen#62]
Don't know if this happens to others but, in my case, if a add a episode to the playlist for later, the said episode is automatically downloaded as expected. however after a while (a few days i guess) the downloaded file for that episode is eventually deleted automatically and without user intervention, preventing me from listening to it when i am offline.
I have browsed the settings for some relevant one, that disables automatic deletion of downloaded episodes but couldn't find anything... Is there a solution for this problem?

**Comment by FriendFX** [comment]
Same here. I don't have automatic downloading activated at all (Episode auto-download = Never), so I download them whenever I want, manually. After downloading one episode, its icon in the Playlist tab changes from the down-arrow symbol to the play-triangle symbol.

I had a few episodes in my playlist with this triangle and I assumed I could just play them whenever I wanted, but for some of them (even ones that I had previously listened to), when tapped on the triangle to play them, the icon immediately changes back to the down-arrow symbol, suggesting I have to re-download them.

I couldn't find any option that suggests to prevent this either.

**Comment by dcorking** [comment]
Doesn't happen for me. I have version 1.3.6 on Android 4.4.4, and I have had episodes in my playlist for more than 6 months.
I have 'Episode auto-download' set to 'Episodes added to playlist'. If there isn't a suitable code fix, perhaps that setting might meet your needs.

**Comment by einmalfel** [comment]
Hello everybody!
@lothar-mar @FriendFX  , please, let me know what version of Android your devices run

**Comment by FriendFX** [comment]
Hi @einmalfel , my phone is running Android version 6.0.1

**Comment by einmalfel** [comment]
@FriendFX thanks for reply. The problem was reported several times, always for Android 6+ devices. My guess is that Android's "Download manager" app has some bug on these versions of Android, causing it to delete old downloads. Possible solution could be to download podcast media to temporary location, then move it to PodListen storage, so Download Manager will not know it's location. I'll try to push such fix to GPlay/Fdroid before weekend.

**Comment by FriendFX** [comment]
@einmalfel Thanks for looking into this. I am a bit unsure what you're saying about the Download Manager app - are you using this from PodListen to fetch the podcast episodes? Or is it just that Download Manager deletes files from the Downloads folder by itself? If you could clarify, I am intending to ask a question about it on https://android.stackexchange.com/ as this sounds like a rather serious flaw.

**Comment by lothar-mar** [comment]
Hi. I am running 7.0

**Comment by dcorking** [comment]
Since I posted above, I have observed this occasionally (episode in playlist, but Play icon changes to Download icon as soon as I tap it), but don't know what circumstances it occurs in. I just wait until I am on online again, and tap the episode's Download icon again. ~Until we can come up with a reproducible case I guess this bug (if it is a bug) will have to stay closed.~
**Update** _never mind, on first read I missed the link to the commit merge earlier. Thanks for the fix, I look forward to seeing it in the app stores_ 😸 
(version 1.3.6 on Android 4.4.4)
