### ISSUE TITLE
Cannot change episode cache directory

### ISSUE THREAD

**Issue by bugmenot2** [einmalfel/PodListen#8]
There's only one option with a radio button in options.
I'd like to keep episodes on my external SD card instead of on my phone.

**Comment by einmalfel** [comment]
Sadly, Android API part related to external storages seems to behave a little differently across various devices and Android builds.
With your help, I'll make an attempt to adapt the code for your device.
For a start, please press "Send bug-report" button in settings screen so I get info about your device and android version you are running.

**Comment by bugmenot2** [comment]
That's kind of you, but I'd still be much more comfortable providing you with the info you need myself. Excuse my paranoia. If you would, please mention all the key-value pairs you need from the report, so I can edit all others out. I'll understand if you decide that's too bothersome.

**Comment by einmalfel** [comment]
@bugmenot2 I suppose this bug is specific to your device or your ROM, because other users don't complain about it. My plan was to search web first to find if someone already solved this problem for your device. So, I need at least your phone model. Also, Android version could help. Do you use preinstalled ROM, or a custom one?
Another thing I wanted to check is a version of PodListen (you can find it in bug-report text, key "default.acra.lastVersionNr"), cause I have recently fixed a problem related to permissions on Android M which (unlikely, but..) could cause your problem.
Bug-report includes log after all, I wanted to check if there was any error in it, that can point to the issue.

**Comment by bugmenot2** [comment]
Sent to e-mail.

**Comment by einmalfel** [comment]
Thanks, @bugmenot2 !
I’ve made an attempt to fix storage switching for Android versions 4.1-4.3.
Update (v1.2.3) is live on Google Play and will be available on F-Droid within 24 hours.
Please, confirm that you are able to switch to SD-card storage after installing it.

P.S. Be aware, podcasts media files will be deleted and redownloaded if you switch storage path

**Comment by bugmenot2** [comment]
Will check when it gets to F-Droid. I copied data to the external card. Will choosing the destination directory for the cache prevent redownload?

**Comment by einmalfel** [comment]
@bugmenot2 I'm afraid it won't: storage switching resets download state in episodes database

**Comment by bugmenot2** [comment]
Are you sure you've submitted it to f-droid? It's been over 24hrs with no update. I don't eve see the app in the queue.
P.S. Is the episodes database not in the same (super)directory?

**Comment by einmalfel** [comment]
@bugmenot2 
I said about 24 hours because the only thing F-Droid documentation says is that builds happen once per a day. F-Droid [has built](https://f-droid.org/wiki/page/com.einmalfel.podlisten/lastbuild_10203) the package 10 hours ago. Apparently there is some more latency on their side before update gets to users. Seems like I shouldn't promise updates in 24h, sorry.

Regarding database - no, podcasts media and database never even appear on same flash partition.

**Comment by bugmenot2** [comment]
Oh yeah, so much free space.
Works, thanks. :)

**Comment by einmalfel** [comment]
Thanks for testing, closing the issue..
